name: 'Evolve Yoga & Fitness'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44316
title: Evolve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fcb040'
    - '#fff205'
    - '#f68420'
  brandStrength: 0
  lightness: 0.9633489942643791
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
