name: 'Evolve Yoga & Fitness'
favicon: null
layout_spectrum: 0.0009091298561543226
typography_spectrum: 0.3136329189874232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7338391931261867
  lightness: 0.9633489942643791
  saturation: 0.37333265971392393
  rhythmicContrast: 0.2522787021007389
purpose: []
